from __future__ import annotations

from typing import Any, cast

import os

os.environ['XLA_PYTHON_CLIENT_PREALLOCATE'] = 'false'

from a0_new.protocols.model import RecursiveFullOnRawModel, T_nn_model, RawModel, FullModelOnRaw, FullModelOnFull
from a0_new.protocols.game import A0Game
from a0_new.protocols.player import FullModelPlayer

from multiprocessing import Process, Queue, Array, Event, Value
from multiprocessing.sharedctypes import Synchronized, SynchronizedArray
from multiprocessing.synchronize import Event as EventType

import pickle
import dill

import numpy as np
from numpy.typing import NDArray

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    # This class exists specifically for type hinting
    from multiprocessing.queues import Queue

from a0_new.models.dynamic_batching import DynamicBatchingModelClient, InferenceRequest, InferenceResponse, DynamicBatchingModelServer
from a0_new.experience_buffer import ExperienceBuffer, ExperienceData
from a0_new.play import play, GameData
from a0_new.utils.model import get_full_on_raw_from_player, get_nn_model_from_player, set_raw_model_to_player

from config import config
from utils.log import get_logger, setup_logging
logger = get_logger(__name__)

def gamedata_to_experiencedata(gamedata: GameData, model: FullModelOnRaw[Any, Any, Any]) -> list[ExperienceData]:
    '''
    Converts a game data object generated by a game into a training set.
    Each turn in the game data is transformed into a training example.
    '''
    experiencedata_list: list[ExperienceData] = []
    game_winner = gamedata.winner
    turn_data = gamedata.turn_data
    for turn in turn_data:
        # get the state
        state = turn.state
        actions = turn.actions

        # get the raw state representation
        raw_state = model.get_raw_state(state)

        # get the outcome of the game for the current player
        current_player = state.get_current_player()
        if game_winner is None:
            # draws and unfinished games
            value = 0.0
        else:
            # 1 for win, -1 for loss
            # based on the perspective of the current player
            value = 1.0 if game_winner == current_player else -1.0
        
        # get the policy distribution generated by MCTS
        policy: NDArray[np.float32] = model.get_raw_policy(state, turn.policy, for_model=True)

        # get the mask for legal moves
        mask = model.get_legal_actions_mask(state, list(actions), for_model=True)

        # create an experience data object
        experiencedata: ExperienceData = ExperienceData(
            state=raw_state,
            value=value,
            policy=policy,
            mask=mask
        )
        
        # add it to the experience data list
        experiencedata_list.append(experiencedata)

    return experiencedata_list

def _gpu_server_process(
        serialized_model: bytes,
        inference_queue: Queue[InferenceRequest],
        response_queues: dict[int, Queue[InferenceResponse]],
        num_active_clients: Synchronized[int],
        num_clients: int,
        max_batch_size: int
    ) -> None:
    setup_logging(
        level=20,
        log_dir=config.log_dir,
        process_name="gpu_server"
    )
    logger.info("GPU server process started")
    # deserialize the model the server will use for inference
    model: RawModel = dill.loads(serialized_model)
    # create and start the dynamic batching server
    server = DynamicBatchingModelServer(
        model,
        inference_queue,
        response_queues,
        num_active_clients=num_active_clients,
        max_batch_size=max_batch_size
    )
    server.serve()
    logger.info("GPU server process shutting down")

def _play_process(
        game: A0Game[Any, Any],
        player: FullModelPlayer[RecursiveFullOnRawModel[Any], Any, Any],
        state_counter: SynchronizedArray[int],
        result_queue: Queue[tuple[GameData, list[ExperienceData]]],
        num_active_workers: Synchronized[int],
        shutdown_event: EventType,
        pid: int
    ) -> None:
    setup_logging(
        level=20,
        log_dir=config.log_dir,
        process_name="play_process_" + str(pid)
    )
    logger.info(f"Play process {pid} started")

    # get the full model on raw from the player,
    # to use its methods for processing gamedata into experience data
    player_for_model = get_full_on_raw_from_player(player)
    while True:
        # play a game
        gamedata = play(
            game,
            [player, player],
            turn_limit=config.turn_limit,
            stop_signal=shutdown_event
        )

        # don't proceed if shutdown event is set
        # we don't want games that didn't finish because of the shutdown signal
        if shutdown_event.is_set():
            logger.info(f"Play process {pid} received shutdown signal, stopping...")
            break

        # update the state counter
        logger.info(f"Play process {pid} finished a game, processing results...")
        num_states = len(gamedata.turn_data)
        with state_counter.get_lock():
            state_counter[pid] += num_states
        # get experience data from gamedata
        experience_data_list = gamedata_to_experiencedata(gamedata, player_for_model)
        logger.info(f"Play process {pid} generated {len(experience_data_list)} experience data entries")

        # send the results back to the main process
        # blocking
        logger.info(f"Play process {pid} sending results to main process...")
        result_queue.put((gamedata, experience_data_list))
    
    with num_active_workers.get_lock():
        num_active_workers.value -= 1
    logger.info(f"Play process {pid} shutting down, active workers remaining: {num_active_workers.value}")

def self_play(
        game: A0Game[Any, Any],
        player: FullModelPlayer[RecursiveFullOnRawModel[T_nn_model], Any, Any],
        experience_buffer: ExperienceBuffer,
        iteration: int
    ) -> None:
    # gamedata list
    gamedata_list: list[GameData] = []

    # get and serialize the raw nn model the player is using
    logger.info("Serializing player model for GPU server...")
    player_nn_model = get_nn_model_from_player(player)
    serialized_nn_model = dill.dumps(player_nn_model)

    # get the number of clients to use, create the queues and shared variables
    logger.info(f"Setting up multiprocessing IPC with {config.num_workers} workers...")
    num_workers = config.num_workers
    inference_queue: Queue[InferenceRequest] = Queue(maxsize=num_workers)
    response_queues: dict[int, Queue[InferenceResponse]] = {
        i: Queue(maxsize=1) for i in range(num_workers)
    }
    result_queue: Queue[tuple[GameData, list[ExperienceData]]] = Queue(maxsize=num_workers)
    num_active_workers: Synchronized[int] = Value('i', 0)
    state_counter: SynchronizedArray[int] = Array('i', [0] * num_workers)
    shutdown_event = Event()

    # start the GPU server process,
    # which will use the given player model for inference
    logger.info("Starting GPU server...")
    server_process = Process(
        target=_gpu_server_process,
        args=(serialized_nn_model, inference_queue, response_queues, num_active_workers, num_workers, config.self_play_batch_size)
    )
    server_process.start()

    # start the play processes,
    # which will send inference requests to the server
    # and game results back to the main process
    logger.info("Starting play processes...")
    processes: list[Process] = []
    for i in range(num_workers):
        logger.info(f"Setting up and starting play process {i}...")
        res_q = response_queues[i]
        # first, create the raw model client for the player
        client = DynamicBatchingModelClient(
            inference_queue, res_q, i, req_timeout=5, res_timeout=5
        )
        # replace the raw model in the player with the client
        set_raw_model_to_player(player, client)
        # start the play process with the player using the client model
        with num_active_workers.get_lock():
            num_active_workers.value += 1
        p = Process(
            target=_play_process,
            args=(game, player, state_counter, result_queue, num_active_workers, shutdown_event, i)
        )
        p.start()
        processes.append(p)
    
    # process results and coordinate shutdown
    logger.info("Main process entering result processing loop...")
    while True:
        # process self-play results as they come in,
        # add to gamedata list and experience buffer
        gamedata, experience_data_list = result_queue.get()
        gamedata_list.append(gamedata)
        for experience_data in experience_data_list:
            experience_buffer.add(experience_data)
        
        # check for shutdown condition
        with state_counter.get_lock():
            # get the total number of states played so far
            total_states = sum(list(state_counter))
            # if enough, set the shutdown event
            if total_states >= config.training_samples:
                logger.info(f"Total states played {total_states} reached the training sample target {config.training_samples}, sending shutdown signal to play processes...")
                shutdown_event.set()
            # log state counts
            state_str = f"Num States Played ({total_states}/{config.training_samples}): "
            for _, count in enumerate(state_counter):
                state_str += f"{count} | "
            logger.info(state_str)
            # break the loop if shutdown event is set
            if shutdown_event.is_set():
                break
        
    logger.info("Main process finished result processing loop, waiting for play processes to shut down...")
    
    # wait for all play processes to finish
    for p in processes:
        # note: join() is blocking,
        # and waits for the processes in order
        # can't decrement num_active_workers here.
        p.join()
        logger.info(f"Play process {p.pid} has shut down.")
    
    # Send shutdown signal to server
    logger.info("Sending shutdown signal to GPU server...")
    shutdown_request = InferenceRequest(
        states=np.empty((0, config.board_size, config.board_size, 2), dtype=np.float32),
        qid=0, nonce=0, shutdown=True
    )
    inference_queue.put(shutdown_request)

    # save the game data to disk
    logger.info("Saving game data to disk...")
    if config.training_dir:
        with open(config.training_dir + f"gamedata_{iteration + 1}.pkl", 'wb') as f:
            pickle.dump(gamedata_list, f)
    
    # put the original model back to the player
    set_raw_model_to_player(player, player_nn_model)
    logger.info("Original model restored to player.")

    # wait for the server process to finish
    logger.info("Waiting for GPU server process to shut down...")
    server_process.join()
