from __future__ import annotations

from typing import Any, cast

import os

os.environ['XLA_PYTHON_CLIENT_PREALLOCATE'] = 'false'

from a0_new.protocols.model import RecursiveFullOnRawModel, T_nn_model, RawModel, FullModelOnRaw, FullModelOnFull
from a0_new.protocols.game import A0Game
from a0_new.protocols.player import FullModelPlayer

from multiprocessing import Process, Queue, Array, Event
from multiprocessing.sharedctypes import SynchronizedArray
from multiprocessing.synchronize import Event as EventType

import pickle
import dill

import numpy as np
from numpy.typing import NDArray

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    # This class exists specifically for type hinting
    from multiprocessing.queues import Queue

from a0_new.models.dynamic_batching import DynamicBatchingModelClient, InferenceRequest, InferenceResponse, DynamicBatchingModelServer
from a0_new.experience_buffer import ExperienceBuffer, ExperienceData
from a0_new.play import play, GameData

from config import config
from utils.log import get_logger, setup_logging
logger = get_logger(__name__)

def gamedata_to_experiencedata(gamedata: GameData, model: FullModelOnRaw[Any, Any, Any]) -> list[ExperienceData]:
    '''
    Converts a game data object generated by a game into a training set.
    Each turn in the game data is transformed into a training example.
    '''
    experiencedata_list: list[ExperienceData] = []
    game_winner = gamedata.winner
    turn_data = gamedata.turn_data
    for turn in turn_data:
        # get the state
        state = turn.state
        actions = turn.actions

        # get the raw state representation
        raw_state = model.get_raw_state(state)

        # get the outcome of the game for the current player
        current_player = state.get_current_player()
        if game_winner is None:
            # draws and unfinished games
            value = 0.0
        else:
            # 1 for win, -1 for loss
            # based on the perspective of the current player
            value = 1.0 if game_winner == current_player else -1.0
        
        # get the policy distribution generated by MCTS
        policy: NDArray[np.float32] = model.get_raw_policy(state, turn.policy, for_model=True)

        # get the mask for legal moves
        mask = model.get_legal_actions_mask(state, list(actions), for_model=True)

        # create an experience data object
        experiencedata: ExperienceData = ExperienceData(
            state=raw_state,
            value=value,
            policy=policy,
            mask=mask
        )
        
        # add it to the experience data list
        experiencedata_list.append(experiencedata)

    return experiencedata_list

def _gpu_server_process(
        serialized_model: bytes,
        inference_queue: Queue[InferenceRequest],
        response_queues: dict[int, Queue[InferenceResponse]],
        num_clients: int
    ) -> None:
    # deserialize the model the server will use for inference
    model: RawModel = dill.loads(serialized_model)
    # create and start the dynamic batching server
    server = DynamicBatchingModelServer(
        model, inference_queue, response_queues, max_batch_size=num_clients, timeout=1
    )
    server.serve()

def _play_process(
        game: A0Game[Any, Any],
        player: FullModelPlayer[RecursiveFullOnRawModel[Any], Any, Any],
        state_counter: SynchronizedArray[int],
        result_queue: Queue[tuple[GameData, list[ExperienceData]]],
        shutdown_event: EventType,
        pid: int
    ) -> None:
    while True:
        player_for_model = get_full_on_raw_from_player(player)

        # play a game
        gamedata = play(
            game,
            [player, player],
            turn_limit=config.turn_limit,
            stop_signal=shutdown_event
        )

        # don't proceed if shutdown event is set
        # we don't want games that didn't finish because of the shutdown signal
        if shutdown_event.is_set():
            break

        # update the state counter
        num_states = len(gamedata.turn_data)
        with state_counter.get_lock():
            state_counter[pid] += num_states
        
        # get experience data from gamedata
        experience_data_list = gamedata_to_experiencedata(gamedata, player_for_model)

        # send the results back to the main process
        # blocking
        result_queue.put((gamedata, experience_data_list))

def get_full_on_raw_from_player(
        player: FullModelPlayer[RecursiveFullOnRawModel[Any], Any, Any]
    ) -> FullModelOnRaw[Any, Any, Any]:
    # get the full model from the player
    model: RecursiveFullOnRawModel[Any] = player.get_model()
    # Navigate through FullModelOnFull wrappers to reach the FullModelOnRaw
    while hasattr(model, 'get_full_model'):
        model = cast(FullModelOnFull[RecursiveFullOnRawModel[Any], Any, Any], model).get_full_model()
    # Now model is a FullModelOnRaw, return it
    return cast(FullModelOnRaw[Any, Any, Any], model)

def get_nn_model_from_player(
        player: FullModelPlayer[RecursiveFullOnRawModel[T_nn_model], Any, Any]
    ) -> T_nn_model:
    # get the full model from the player
    model: RecursiveFullOnRawModel[T_nn_model] = player.get_model()
    # Navigate through FullModelOnFull wrappers to reach the FullModelOnRaw
    while hasattr(model, 'get_full_model'):
        model = cast(FullModelOnFull[RecursiveFullOnRawModel[T_nn_model], Any, Any], model).get_full_model()
    # Now model is a FullModelOnRaw, return its raw model (the NNModel)
    return cast(FullModelOnRaw[T_nn_model, Any, Any], model).get_raw_model()

def set_raw_model_to_player(
        player: FullModelPlayer[RecursiveFullOnRawModel[Any], Any, Any],
        raw_model: RawModel
    ) -> None:
    # get the full model from the player
    model: RecursiveFullOnRawModel[Any] = player.get_model()
    # Navigate through FullModelOnFull wrappers to reach the FullModelOnRaw
    while hasattr(model, 'get_full_model'):
        model = cast(FullModelOnFull[RecursiveFullOnRawModel[Any], Any, Any], model).get_full_model()
    # Now model is a FullModelOnRaw, set its raw model
    cast(FullModelOnRaw[Any, Any, Any], model).set_raw_model(raw_model)

def self_play(
        game: A0Game[Any, Any],
        player: FullModelPlayer[RecursiveFullOnRawModel[T_nn_model], Any, Any],
        experience_buffer: ExperienceBuffer,
        iteration: int
    ) -> None:
    # gamedata list
    gamedata_list: list[GameData] = []

    # get and serialize the raw nn model the player is using
    player_nn_model = get_nn_model_from_player(player)
    serialized_nn_model = dill.dumps(player_nn_model)

    # get the number of clients to use, create the queues and shared variables
    num_workers = config.num_workers
    inference_queue: Queue[InferenceRequest] = Queue(maxsize=num_workers)
    response_queues: dict[int, Queue[InferenceResponse]] = {
        i: Queue(maxsize=1) for i in range(num_workers)
    }
    result_queue: Queue[tuple[GameData, list[ExperienceData]]] = Queue(maxsize=num_workers)
    state_counter: SynchronizedArray[int] = Array('i', [0] * num_workers)
    shutdown_event = Event()

    # start the GPU server process,
    # which will use the given player model for inference
    server_process = Process(
        target=_gpu_server_process,
        args=(serialized_nn_model, inference_queue, response_queues, num_workers)
    )
    server_process.start()

    # start the play processes,
    # which will send inference requests to the server
    # and game results back to the main process
    processes: list[Process] = []
    for i in range(num_workers):
        res_q = response_queues[i]
        # first, create the raw model client for the player
        client = DynamicBatchingModelClient(
            inference_queue, res_q, i, req_timeout=5, res_timeout=5
        )
        # replace the raw model in the player with the client
        set_raw_model_to_player(player, client)
        # start the play process with the player using the client model
        p = Process(
            target=_play_process,
            args=(game, player, state_counter, result_queue, shutdown_event, i)
        )
        p.start()
        processes.append(p)
    
    # process results and coordinate shutdown
    while True:
        # process self-play results as they come in,
        # add to gamedata list and experience buffer
        gamedata, experience_data_list = result_queue.get()
        gamedata_list.append(gamedata)
        for experience_data in experience_data_list:
            experience_buffer.add(experience_data)
        
        # check for shutdown condition
        with state_counter.get_lock():
            # get the total number of states played so far
            total_states = sum(list(state_counter))
            # if enough, set the shutdown event
            if total_states >= config.training_samples:
                shutdown_event.set()
            # log state counts
            state_str = f"Total states played: {total_states}: "
            for _, count in enumerate(state_counter):
                state_str += f"{count} "
            logger.info(state_str)
            # break the loop if shutdown event is set
            if shutdown_event.is_set():
                break
    
    # wait for all play processes to finish
    for p in processes:
        p.join()
    
    # Send shutdown signal to server
    shutdown_request = InferenceRequest(
        states=np.empty((0, config.board_size, config.board_size, 2), dtype=np.float32),
        qid=0, nonce=0, shutdown=True
    )
    inference_queue.put(shutdown_request)

    # save the game data to disk
    if config.training_dir:
        with open(config.training_dir + f"gamedata_{iteration + 1}.pkl", 'wb') as f:
            pickle.dump(gamedata_list, f)
    
    # put the original model back to the player
    set_raw_model_to_player(player, player_nn_model)

    # wait for the server process to finish
    server_process.join()
