from typing import Optional, Any
import multiprocessing
import concurrent.futures
from concurrent.futures import Future, wait, FIRST_COMPLETED
import os
import pickle
import dill

import jax
from flax import nnx
import jax.numpy as jnp
import optax

from config import config

from a0.game import play, GameData
from a0.players.a0 import A0Player
from a0.model_utils import board_to_input
from a0.model import AlphaZeroModel, load_model, save_model
from cc.core import Game
from cc.ground_truth import GroundTruth
from a0.train.dataset import train_model_epochs, plot_model_performance, DatasetData, save_dataset_data, stats_from_dataset_data
from a0.eval.training_data import GameDataStats, game_data_list_stats
from a0.experience_buffer import ExperienceBuffer, ExperienceData

from utils.log import get_logger, setup_logging
logger = get_logger(__name__)

def game_data_to_training_set(game_data: GameData) -> list[ExperienceData]:
    '''
    Converts a game data object generated by a game into a training set.
    Each turn in the game data is transformed into a training example.
    '''
    training_set: list[ExperienceData] = []
    # get the game data and transform it into training data
    game_winner = game_data.winner
    
    turn_data = game_data.turn_data
    for turn in turn_data:
        # get the board state
        board = turn.board

        # get the outcome of the game for the current player
        current_player = board.current_player
        if game_winner is None:
            # draws and unfinished games
            value = 0.0
        else:
            # 1 for win, -1 for loss
            # based on the perspective of the current player
            value = 1.0 if game_winner == current_player else -1.0
        
        # get the policy distribution generated by MCTS
        mcts_policy: jnp.ndarray = turn.player_data
        
        # create a training example
        training_example: ExperienceData = ExperienceData(
            board=jnp.array(board_to_input(board)),
            value=value,
            policy=mcts_policy
        )
        
        # add it to the training set
        training_set.append(training_example)

    return training_set

def game_data_to_gt_training_set(game_data: GameData) -> list[ExperienceData]:
    '''
    Converts a game data object generated by a game into a training set.
    Each turn in the game data is transformed into a training example.
    Except this function uses the ground truth data for the value/policy at each state,
    rather than the "experienced" outcome/policy.
    '''
    gt = GroundTruth()
    training_set: list[ExperienceData] = []
    
    turn_data = game_data.turn_data
    for turn in turn_data:
        # get the board state
        board = turn.board

        # get the gt outcome of the board for the current player
        value = gt.get_outcome(board)
        
        # get the gt policy distribution
        mcts_policy: jnp.ndarray = jnp.array(gt.get_1ply_policy_prob_dist_list(board, for_model=True))

        # create a training example
        training_example: ExperienceData = ExperienceData(
            board=jnp.array(board_to_input(board)),
            value=value,
            policy=mcts_policy
        )
        
        # add it to the training set
        training_set.append(training_example)

    return training_set

def _play(serialized_player: bytes) -> tuple[list[ExperienceData], GameData]:
    '''
    Plays a game of chinese checkers with the given players,
    then converts the game data into a training set.
    This function returns both the training set and the game data.
    '''
    # first, set up logging (since this is a separate process)
    setup_logging(
        level=20,
        log_dir=config.log_dir,
        process_name="training_alphazero"
    )
    # then play the game
    game = Game(
        board_size=config.board_size,
        num_pieces=config.num_pieces,
        repeats_for_draw=config.repeats_for_draw,
        no_reverse_moves=False,
        no_illegal_moves=False,
        no_side_moves=False
    )
    player: A0Player = dill.loads(serialized_player)
    game_data = play(game, [player, player], config.turn_limit)
    return game_data_to_training_set(game_data), game_data

def self_play(player: A0Player) -> tuple[list[ExperienceData], list[GameData]]:
    '''
    Runs self-play to generate a training set for the AlphaZero model.
    This function uses multiprocessing to run multiple games in parallel.
    The training set is generated from the game data, which is then returned.
    The game data can also be saved to a file if a filepath is provided.
    Args:
        player (A0Player): The player to use for self-play.
    Returns:
        The generated training set, containing board states, values, and policies.
        The game data for each game played, which can be used for analysis or debugging.
    '''
    logger.info("Starting self-play to generate training data...")
    # serialize the player model (JAX models cannot be pickled directly + serialization is needed for multiprocessing)
    player_serialized: bytes = dill.dumps(player)
    # use self-play with the model and mcts to generate training data
    # run each game in parallel
    game_data_list: list[GameData] = []
    training_set: list[ExperienceData] = []
    num_cores = os.cpu_count() or 4
    logger.info(f"Using {num_cores} cores for self-play.")
    with concurrent.futures.ProcessPoolExecutor() as executor:
        # create a list to hold the futures
        futures: list[Future[tuple[list[ExperienceData], GameData]]] = []

        # create a function to start a game
        def start_game() -> None:
            future = executor.submit(
                _play,
                serialized_player=player_serialized
            )
            futures.append(future)
        
        # start a game for each core
        for _ in range(num_cores):
            start_game()
        
        while True:
            logger.info(f"Current training set size: {len(training_set)}/{config.training_samples}")
            # when a game (or games) finish(es),
            done, _ = wait(futures, return_when=FIRST_COMPLETED)

            # for each finished game,
            for future in done:
                # remove it from the list of futures
                futures.remove(future)
                # get the training data and game data from the game
                game_training_set, game_data = future.result()
                # add the training data to the training set
                training_set.extend(game_training_set)
                # and the game data to the list of game data
                game_data_list.append(game_data)
                # if the training set is not full yet, start a new game
                if len(training_set) < config.training_samples:
                    start_game()
            
            # stop when the training set is full
            if len(training_set) >= config.training_samples:
                logger.info("Training set is full, cancelling all games.")
                # cancel any submitted but not yet started games
                for future in futures:
                    future.cancel()
                # note the following does not immediately stop all processes,
                # but prevents new tasks from being started
                # and frees this main process to continue
                # the remaining games/processes finish in the background
                # executor.shutdown(wait=False)
                break
    
    logger.info(f"Generated training set of size: {len(training_set)}/{config.training_samples}")
    return training_set, game_data_list

def train_alphazero(model_path: Optional[str], starting_iteration: int=0) -> None:
    os.makedirs(config.plot_dir + "training_plots", exist_ok=True)
    
    iterations = config.training_iterations
    # create/load a model
    model = AlphaZeroModel(
        config.board_size,
        training=config.model_training,
        rngs=nnx.Rngs({'params': jax.random.PRNGKey(0)})
    )
    if model_path:
        model = load_model(model_path)
    
    if config.training_dir:
        save_model(config.training_dir + f'/model_{0}.pkl', model)
    
    experience_buffer = ExperienceBuffer(
        config.replay_buffer_size
    )

    train_datas: list[DatasetData] = []
    logger.log(25, GameDataStats.get_header())
    for i in range(starting_iteration, iterations):
        print(f"Iteration {i + 1}/{iterations}")
        logger.info(f"Iteration {i + 1}/{iterations}")
        # create a player with the current model
        player = A0Player(
            config.board_size,
            config.num_pieces,
            model,
            mcts_samples=config.mcts_samples,
            no_reverse_moves=not config.backwards_moves,
            no_side_moves=not config.sideways_moves
        )

        # generate training data with self-play
        training_set, game_data = self_play(player)

        # generate and print stats about the game data
        game_data_stats = game_data_list_stats(i, game_data)
        logger.log(25, f"{game_data_stats.get_line()}")
        
        # save the game data to a file
        if config.training_dir:
            with open(config.training_dir + f"gamedata_{i + 1}.pkl", 'wb') as f:
                pickle.dump(game_data, f)
        
        # add the training data to the replay buffer
        for example in training_set:
            experience_buffer.add(example)
        
        # train the model on the experiences in the replay buffer
        model, train_data = train_model_epochs(
            model=model,
            dataset=experience_buffer.get_dataset(config.training_batch_size),
            num_epochs=1,
            save="none",
            plot=False,
            test_datasets={}
        )
        train_datas.append(train_data)

        # plot, log, and save the model performance metrics in this iteration's training
        plot_model_performance(f"training_plots/iteration_{i + 1}", [train_data])
        save_dataset_data(
            f"{config.training_dir}/iteration_stats_{i + 1}.pkl",
            train_data
        )
        total, value_loss, policy_loss, value_accuracy, policy_accuracy = stats_from_dataset_data(train_data)
        logger.log(25, f"Iteration {i + 1} stats: Total Loss: {total:.4f}, Value Loss: {value_loss:.4f}, Policy Loss: {policy_loss:.4f}, Value Accuracy: {value_accuracy:.2%}, Policy Accuracy: {policy_accuracy:.2%}")

        # save the model after each iteration
        if config.training_dir:
            save_model(config.training_dir + f'model_{i + 1}.pkl', model)
    
    # after all iterations, plot all the training data
    plot_model_performance("training_plots/full_a0", train_datas)

if __name__ == "__main__":
    setup_logging(
        level=20,
        log_dir=config.log_dir,
        process_name="training_alphazero"
    )

    logger.info(f"config: {config.path}")

    # Set the multiprocessing start method to 'spawn' for compatibility with JAX
    try:
        multiprocessing.set_start_method('spawn')
    except RuntimeError:
        pass

    # Example usage
    train_alphazero(
        model_path=None
    )
