from typing import Optional, Any
import concurrent.futures
from concurrent.futures import Future, wait, FIRST_COMPLETED
import os
import pickle
import dill

import jax
from flax import nnx
import jax.numpy as jnp
import optax

from config import config

from a0.game import play, GameData
from a0.players.a0 import A0Player, board_to_input
from a0.model import AlphaZeroModel, load_model, save_model
from cc.core import Game

from utils.log import get_logger, setup_logging
logger = get_logger(__name__)

class TrainingData:
    def __init__(self, board: jnp.ndarray, value: float, policy: jnp.ndarray):
        self.board: jnp.ndarray = board
        self.value: float = value
        self.policy: jnp.ndarray = policy

def game_data_to_training_set(game_data: GameData) -> list[TrainingData]:
    '''
    Converts a game data object generated by a game into a training set.
    Each turn in the game data is transformed into a training example.
    '''
    training_set: list[TrainingData] = []
    # get the game data and transform it into training data
    game_winner = game_data.winner
    
    turn_data = game_data.turn_data
    for turn in turn_data:
        # get the board state
        board = turn.board

        # get the outcome of the game for the current player
        current_player = board.current_player
        if game_winner is None:
            # draws and unfinished games
            value = 0.0
        else:
            # 1 for win, -1 for loss
            # based on the perspective of the current player
            value = 1.0 if game_winner == current_player else -1.0
        
        # get the policy distribution generated by MCTS
        mcts_policy: jnp.ndarray = turn.player_data
        
        # create a training example
        training_example: TrainingData = TrainingData(
            board=board_to_input(board),
            value=value,
            policy=mcts_policy
        )
        
        # add it to the training set
        training_set.append(training_example)

    return training_set

def _play(player: bytes) -> tuple[list[TrainingData], GameData]:
    '''
    Plays a game of chinese checkers with the given players,
    then converts the game data into a training set.
    This function returns both the training set and the game data.
    '''
    game = Game(config.board_size, config.num_pieces, True, False)
    player: A0Player = dill.loads(player)
    game_data = play(game, [player, player], config.turn_limit)
    return game_data_to_training_set(game_data), game_data

def self_play(player: A0Player) -> tuple[list[TrainingData], list[GameData]]:
    '''
    Runs self-play to generate a training set for the AlphaZero model.
    This function uses multiprocessing to run multiple games in parallel.
    The training set is generated from the game data, which is then returned.
    The game data can also be saved to a file if a filepath is provided.
    Args:
        player (A0Player): The player to use for self-play.
    Returns:
        The generated training set, containing board states, values, and policies.
        The game data for each game played, which can be used for analysis or debugging.
    '''
    logger.info("Starting self-play to generate training data...")
    print("Starting self-play to generate training data...")
    # serialize the player model (JAX models cannot be pickled directly + serialization is needed for multiprocessing)
    player_serialized: bytes = dill.dumps(player)
    # use self-play with the model and mcts to generate training data
    # run each game in parallel
    game_data_list: list[GameData] = []
    training_set: list[TrainingData] = []
    num_cores = os.cpu_count() or 4
    with concurrent.futures.ProcessPoolExecutor() as executor:
        futures: list[Future[tuple[list[TrainingData], GameData]]] = []

        def start_game() -> None:
            future = executor.submit(
                _play,
                player=player_serialized
            )
            futures.append(future)
        
        # start a game for each core
        for _ in range(num_cores):
            start_game()
        
        while True:
            # when a game (or games) finish(es),
            done, _ = wait(futures, return_when=FIRST_COMPLETED)

            # for each finished game,
            for future in done:
                # remove it from the list of futures
                futures.remove(future)
                # get the training data and game data from the game
                game_training_set, game_data = future.result()
                # add the training data to the training set
                training_set.extend(game_training_set)
                # and the game data to the list of game data
                game_data_list.append(game_data)
                # if the training set is not full yet, start a new game
                if len(training_set) >= config.training_samples:
                    start_game()
            
            # stop when the training set is full
            if len(training_set) >= config.training_samples:
                print("Training set is full, cancelling all games")
                for future in futures:
                    future.cancel()
                break
    
    print(f"Generated training set of size: {len(training_set)}/{config.training_samples}")
    return training_set[:config.training_samples], game_data_list

def train_model(model: AlphaZeroModel, training_set: list[TrainingData], n_batches: int = 10) -> AlphaZeroModel:
    logger.info("Training model on the generated training set...")
    boards = jnp.stack([jnp.array(ex.board) for ex in training_set])
    values = jnp.array([ex.value for ex in training_set])[:, None]  # Add [:, None] to make its shape (batch_size, 1)
    policies = jnp.stack([jnp.array(ex.policy) for ex in training_set])

    # Split into n_batches (last batch may be smaller)
    total = len(training_set)
    batch_size = total // n_batches
    batches = []
    for i in range(n_batches):
        start = i * batch_size
        end = (i + 1) * batch_size if i < n_batches - 1 else total
        batch = {
            'board': boards[start:end],
            'value': values[start:end],
            'policy': policies[start:end]
        }
        batches.append(batch)

    optimizer = nnx.Optimizer(model, optax.adamw(0.005, 0.9))

    value_loss_function = optax.l2_loss
    policy_loss_function = optax.softmax_cross_entropy

    def loss_fn(model: AlphaZeroModel, batch: dict[str, Any]):
        value, policy = model(batch['board'])
        value_loss = jnp.mean(value_loss_function(value, batch['value']))
        masked_policy = jnp.where(batch['policy'], policy, 0)
        policy_loss = jnp.mean(policy_loss_function(labels=batch['policy'], logits=masked_policy))
        total_loss = value_loss + policy_loss
        # JAX requires the loss function to return a tuple of (loss, aux)
        # where aux can be any additional information you want to return
        return total_loss, (value_loss, policy_loss)
    
    @nnx.jit
    def train_step(model: AlphaZeroModel, optimizer: nnx.Optimizer, batch: dict[str, Any]):
        grad_fn = nnx.value_and_grad(loss_fn, has_aux=True)
        (loss, (value_loss, policy_loss)), grads = grad_fn(model, batch)
        optimizer.update(grads)
        return loss, value_loss, policy_loss
    
    for ts, batch in enumerate(batches):
        loss, value_loss, policy_loss = train_step(model, optimizer, batch)
        logger.info(f"Training Step {ts}, Loss: {loss}, Value Loss: {value_loss}, Policy Loss: {policy_loss}")
        print(f"Training Step {ts}, Loss: {loss}, Value Loss: {value_loss}, Policy Loss: {policy_loss}")

    return model

def train_alphazero(model_path: Optional[str]) -> None:
    iterations = config.training_iterations
    # create/load a model
    model = AlphaZeroModel(
        config.board_size,
        training=False,
        rngs=nnx.Rngs({'params': jax.random.PRNGKey(0)})
    )
    if model_path:
        model = load_model(model_path, model)
    
    if config.training_dir:
        save_model(config.training_dir + f'/model_{0}.pkl', model)

    for i in range(iterations):
        print(f"Iteration {i + 1}/{iterations}")
        logger.info(f"Iteration {i + 1}/{iterations}")
        # create a player with the current model
        player = A0Player(config.board_size, config.num_pieces, model)

        # generate training data with self-play
        training_set, game_data = self_play(player)

        # save the training set to a file
        if config.training_dir:
            with open(config.training_dir + f"training_set_{i}.pkl", 'wb') as f:
                pickle.dump(training_set, f)
        
        # save the game data to a file
        if config.training_dir:
            with open(config.training_dir + "gamedata_{i}.pkl", 'wb') as f:
                pickle.dump(game_data, f)
        
        # train the model on the training set
        model = train_model(model, training_set)
        
        # save the model after each iteration
        if config.training_dir:
            save_model(config.training_dir + f'model_{i + 1}.pkl', model)

if __name__ == "__main__":
    setup_logging(
        level=5,
        log_dir="logs/",
        process_name="training_alphazero"
    )

    # Example usage
    train_alphazero(
        model_path=None
    )
