from typing import Optional, Any
import multiprocessing
import concurrent.futures
from concurrent.futures import Future, wait, FIRST_COMPLETED
import os
os.environ['XLA_PYTHON_CLIENT_PREALLOCATE'] = 'false'
import gc
import pickle
import dill

import jax
from flax import nnx
import numpy as np
import optax

from config import config

from a0.game import play, GameData
from a0.players.a0 import A0Player
from a0.model_utils import board_to_input, get_legal_move_mask_from_state, Policy
from a0.model import AlphaZeroModel, MultiTrunkAlphaZeroModel, load_model, save_model, create_model
from cc.core import Game, Player
from cc.ground_truth import GroundTruth
from a0.train.dataset import train_model_epochs, plot_model_performance, DatasetData, save_dataset_data, stats_from_dataset_data
from a0.eval.training_data import GameDataStats, game_data_list_stats
from a0.experience_buffer import ExperienceBuffer, ExperienceData

from utils.log import get_logger, setup_logging
logger = get_logger(__name__)

def game_data_to_training_set(game_data: GameData) -> list[ExperienceData]:
    '''
    Converts a game data object generated by a game into a training set.
    Each turn in the game data is transformed into a training example.
    '''
    training_set: list[ExperienceData] = []
    # get the game data and transform it into training data
    game_winner = game_data.winner
    
    turn_data = game_data.turn_data
    for turn in turn_data:
        # get the board state
        board = turn.board

        # get the mask for full legal moves
        legal_move_mask = get_legal_move_mask_from_state(board, for_model=True)

        # get the outcome of the game for the current player
        current_player = board.current_player
        if game_winner is None:
            # draws and unfinished games
            value = 0.0
        else:
            # 1 for win, -1 for loss
            # based on the perspective of the current player
            value = 1.0 if game_winner == current_player else -1.0
        
        # get the policy distribution generated by MCTS (already np from Policy class)
        mcts_policy = turn.player_data

        # create a training example
        training_example: ExperienceData = ExperienceData(
            board=board_to_input(board),
            value=value,
            policy=mcts_policy,
            mask=legal_move_mask
        )
        
        # add it to the training set
        training_set.append(training_example)

    return training_set

def game_data_to_gt_training_set(game_data: GameData, gt: GroundTruth | None = None) -> list[ExperienceData]:
    '''
    Converts a game data object generated by a game into a training set.
    Each turn in the game data is transformed into a training example.
    Except this function uses the ground truth data for the value/policy at each state,
    rather than the "experienced" outcome/policy.
    '''
    if gt is None:
        gt = GroundTruth()
    training_set: list[ExperienceData] = []
    
    turn_data = game_data.turn_data
    for turn in turn_data:
        # get the board state
        board = turn.board

        # get the mask for full legal moves
        legal_move_mask = get_legal_move_mask_from_state(board, for_model=True)

        # get the gt outcome of the board for the current player
        value = gt.get_outcome(board)
        
        # get the gt policy distribution (list[float] from GroundTruth, needs np conversion)
        mcts_policy = np.array(gt.get_1ply_policy_prob_dist_list(board, for_model=True), dtype=np.float32)

        # create a training example
        training_example: ExperienceData = ExperienceData(
            board=board_to_input(board),
            value=value,
            policy=mcts_policy,
            mask=legal_move_mask
        )
        
        # add it to the training set
        training_set.append(training_example)

    return training_set

def game_data_to_gt_value_training_set(game_data: GameData, gt: GroundTruth | None = None) -> list[ExperienceData]:
    '''
    Like game_data_to_training_set, but replaces the value with the ground truth
    outcome of the current state. The policy is kept as the MCTS policy.
    '''
    if gt is None:
        gt = GroundTruth()
    training_set: list[ExperienceData] = []

    turn_data = game_data.turn_data
    for turn in turn_data:
        board = turn.board
        legal_move_mask = get_legal_move_mask_from_state(board, for_model=True)

        # GT value for the current state
        value = gt.get_outcome(board)

        # MCTS policy (already in model perspective)
        mcts_policy = turn.player_data

        training_example = ExperienceData(
            board=board_to_input(board),
            value=value,
            policy=mcts_policy,
            mask=legal_move_mask
        )
        training_set.append(training_example)

    return training_set

def game_data_to_gt_next_value_training_set(game_data: GameData, gt: GroundTruth | None = None) -> list[ExperienceData]:
    '''
    Like game_data_to_training_set, but replaces the value with the ground truth
    outcome of the next state, where the top action in the MCTS policy is taken
    on the current state. The policy is kept as the MCTS policy.
    The GT outcome of the next state is from the opponent's perspective,
    so it is negated to stay in the current player's perspective.
    '''
    if gt is None:
        gt = GroundTruth()
    training_set: list[ExperienceData] = []

    turn_data = game_data.turn_data
    for turn in turn_data:
        board = turn.board
        legal_move_mask = get_legal_move_mask_from_state(board, for_model=True)

        # The stored MCTS policy is in model perspective (rotated for PLAYER_O).
        # Un-rotate to find the actual best move on the board.
        mcts_policy = turn.player_data
        p = Policy(len(board.board))
        p.set_logits(mcts_policy.copy(), rotate_180=False)
        if board.current_player == Player.PLAYER_O:
            p.rotate_policy()
        best_move = p.get_best_move()

        # Apply the best move to get the next state
        board.apply_move(best_move)
        # GT outcome from the next state's current player (opponent), negated
        value = -gt.get_outcome(board)
        board.undo_move(best_move)

        training_example = ExperienceData(
            board=board_to_input(board),
            value=value,
            policy=mcts_policy,
            mask=legal_move_mask
        )
        training_set.append(training_example)

    return training_set

def game_data_to_model_value_training_set(game_data: GameData, model: AlphaZeroModel | MultiTrunkAlphaZeroModel) -> list[ExperienceData]:
    '''
    Like game_data_to_training_set, but uses backward-propagated model values as targets.
    The last state's target is the true game outcome. For all earlier states, the target
    is the negated model value of the next state (negated because players alternate).
    The policy is kept as the MCTS policy.
    Also populates turn.alternative_targets["model_value"] on each turn so that
    the model's predictions are saved with the game data.
    '''
    training_set: list[ExperienceData] = []

    turn_data = game_data.turn_data
    if not turn_data:
        return training_set

    # batch all board inputs for a single inference call
    board_inputs = [board_to_input(turn.board) for turn in turn_data]
    boards = np.concatenate(board_inputs, axis=0)
    model_values, _ = model.inference(boards)
    model_values = jax.lax.stop_gradient(model_values)

    # compute targets backward from the last state
    num_turns = len(turn_data)
    targets = [0.0] * num_turns

    # last state: true game outcome from that player's perspective
    game_winner = game_data.winner
    if game_winner is None:
        targets[-1] = 0.0
    else:
        targets[-1] = 1.0 if game_winner == turn_data[-1].board.current_player else -1.0

    # earlier states: negated model value of the next state
    for t in range(num_turns - 2, -1, -1):
        targets[t] = -float(model_values[t + 1][0])

    for turn, board_input, target in zip(turn_data, board_inputs, targets):
        turn.alternative_targets["model_value"] = target

        legal_move_mask = get_legal_move_mask_from_state(turn.board, for_model=True)
        training_example = ExperienceData(
            board=board_input,
            value=target,
            policy=turn.player_data,
            mask=legal_move_mask
        )
        training_set.append(training_example)

    return training_set

def game_data_to_td_lambda_training_set(game_data: GameData, model: AlphaZeroModel | MultiTrunkAlphaZeroModel, lam: float) -> list[ExperienceData]:
    '''
    Uses TD(lambda) targets to blend bootstrapped and Monte Carlo returns.
      - lambda=0: TD(0), target = -V(s_{t+1})
      - lambda=1: Monte Carlo, target = game outcome
    Recursive formula (backward pass):
      G_{T-1} = z_{T-1}
      G_t     = -(1 - lambda) * V[t+1] - lambda * G_{t+1}
    The policy is kept as the MCTS policy.
    '''
    training_set: list[ExperienceData] = []
    turn_data = game_data.turn_data
    if not turn_data:
        return training_set

    # \hat{v}(S_0), \hat{v}(S_1), ..., \hat{v}(S_{T-1}) via batch inference
    # pad to fixed batch size so JAX JIT only compiles one kernel for this path
    FIXED_BATCH_SIZE = 256
    board_inputs = [board_to_input(turn.board) for turn in turn_data]
    boards = np.concatenate(board_inputs, axis=0)
    num_real = boards.shape[0]
    if num_real < FIXED_BATCH_SIZE:
        padding = np.zeros((FIXED_BATCH_SIZE - num_real, *boards.shape[1:]), dtype=boards.dtype)
        boards_padded = np.concatenate([boards, padding], axis=0)
    else:
        boards_padded = boards
    model_values, _ = model.inference(boards_padded)
    model_values = model_values[:num_real]
    model_values = jax.lax.stop_gradient(model_values)

    num_turns = len(turn_data)
    targets = [0.0] * num_turns

    # G_{T-1}^\lambda = z_{T-1}   (game outcome from last player's perspective)
    game_winner = game_data.winner
    if game_winner is None:
        targets[-1] = 0.0
    else:
        targets[-1] = 1.0 if game_winner == turn_data[-1].board.current_player else -1.0

    # G_t^\lambda = -(1 - \lambda) \hat{v}(S_{t+1}) - \lambda G_{t+1}^\lambda
    # Both terms are negated because \hat{v}(S_{t+1}) and G_{t+1}^\lambda
    # are from the next player's (opponent's) perspective.
    for t in range(num_turns - 2, -1, -1):
        v_next = float(model_values[t + 1][0])  # \hat{v}(S_{t+1})
        targets[t] = -(1 - lam) * v_next - lam * targets[t + 1]

    for turn, board_input, target in zip(turn_data, board_inputs, targets):
        turn.alternative_targets["td_lambda"] = target
        legal_move_mask = get_legal_move_mask_from_state(turn.board, for_model=True)
        training_example = ExperienceData(
            board=board_input,
            value=target,
            policy=turn.player_data,
            mask=legal_move_mask
        )
        training_set.append(training_example)

    return training_set

def _log_value_histogram(name: str, values: np.ndarray, n_buckets: int = 10) -> None:
    '''Logs a histogram of values in [-1, 1], matching Dataset.print_bucket_distribution style.'''
    total = len(values)
    if total == 0:
        logger.log(25, f"{name}: empty")
        return
    edges = np.linspace(-1, 1, n_buckets + 1)
    counts = np.histogram(values, bins=edges)[0]
    logger.log(25, f"{name} ({n_buckets} buckets, {total} values):")
    for i in range(n_buckets):
        lo, hi = edges[i], edges[i + 1]
        count = int(counts[i])
        bar = "#" * int(40 * count / max(total, 1))
        logger.log(25, f"  [{lo:+.2f}, {hi:+.2f}{']' if i == n_buckets - 1 else ')'} {count:6d} ({count/total:.2%}) {bar}")

def generate_balanced_gt_eval_dataset(n_samples: int = 1000) -> tuple[np.ndarray, np.ndarray]:
    '''
    Generates a balanced evaluation dataset using ground truth.
    Samples random board states, gets GT values, and balances to
    have equal positive (+1) and negative (-1) values.
    Draws and illegal states are excluded.
    Returns (board_inputs, gt_values) as numpy arrays.
    '''
    gt = GroundTruth()
    max_rank = gt.get_max_rank()

    rng = np.random.default_rng(42)
    sample_size = min(n_samples * 5, max_rank)
    ranks = rng.choice(max_rank, size=sample_size, replace=False)

    boards_list = []
    values_list = []
    for rank in ranks:
        board = gt.unrank(int(rank))
        if gt.is_illegal(board):
            continue
        value = gt.get_outcome(board)
        if value == 0.0:
            continue
        boards_list.append(board_to_input(board))
        values_list.append(value)

    board_inputs = np.concatenate(boards_list, axis=0)
    values = np.array(values_list, dtype=np.float32)

    # Balance: equal positive and negative
    pos_indices = np.where(values > 0)[0]
    neg_indices = np.where(values < 0)[0]
    target_per_side = min(len(pos_indices), len(neg_indices), n_samples // 2)

    selected_pos = rng.choice(pos_indices, size=target_per_side, replace=False)
    selected_neg = rng.choice(neg_indices, size=target_per_side, replace=False)
    selected = np.concatenate([selected_pos, selected_neg])
    rng.shuffle(selected)

    logger.log(25, f"Generated balanced GT eval dataset: {target_per_side} pos, {target_per_side} neg ({target_per_side * 2} total)")

    return board_inputs[selected], values[selected]

def capture_value_diagnostics(
    model: AlphaZeroModel | MultiTrunkAlphaZeroModel,
    pre_balance_values: np.ndarray,
    post_balance_values: np.ndarray,
    gt_eval_boards: np.ndarray,
    gt_eval_values: np.ndarray,
) -> dict[str, list[float]]:
    '''
    Captures value diagnostics for the current training iteration.
    Logs histograms and returns full value lists for later analysis.
    Args:
        model: the current model to get predictions from
        pre_balance_values: flat array of dataset target values before balancing
        post_balance_values: flat array of dataset target values after balancing
        gt_eval_boards: board inputs from the balanced GT eval dataset
        gt_eval_values: GT values from the balanced GT eval dataset
    Returns:
        dict with full value lists for serialization
    '''
    # Model predictions on balanced GT dataset
    model_preds, _ = model.inference(gt_eval_boards)
    model_preds = np.array(model_preds).flatten()

    # Log histograms
    _log_value_histogram("Dataset targets (pre-balance)", pre_balance_values)
    _log_value_histogram("Dataset targets (post-balance)", post_balance_values)
    _log_value_histogram("Model predictions on balanced GT eval", model_preds)

    return {
        'dataset_values_pre': pre_balance_values.tolist(),
        'dataset_values_post': post_balance_values.tolist(),
        'gt_eval_values': gt_eval_values.tolist(),
        'model_predictions': model_preds.tolist(),
    }

def _play(serialized_player: bytes) -> tuple[list[ExperienceData], GameData]:
    '''
    Plays a game of chinese checkers with the given players,
    then converts the game data into a training set.
    This function returns both the training set and the game data.
    '''
    # first, set up logging (since this is a separate process)
    setup_logging(
        level=20,
        log_dir=config.log_dir,
        process_name="training_alphazero"
    )
    # then play the game
    game_has_reverse_moves = config.backwards_moves
    game_has_side_moves = config.sideways_moves
    if config.root_game_has_all_moves:
        game_has_reverse_moves = True
        game_has_side_moves = True
    game = Game(
        board_size=config.board_size,
        num_pieces=config.num_pieces,
        repeats_for_draw=config.repeats_for_draw,
        no_reverse_moves=not game_has_reverse_moves,
        no_illegal_moves=not config.illegal_moves,
        no_side_moves=not game_has_side_moves
    )
    player: A0Player = dill.loads(serialized_player)
    game_data = play(game, [player, player], config.turn_limit)

    if config.experiment == "gt":
        return game_data_to_gt_training_set(game_data), game_data
    elif config.experiment == "gt_value":
        return game_data_to_gt_value_training_set(game_data), game_data
    elif config.experiment == "gt_next_value":
        return game_data_to_gt_next_value_training_set(game_data), game_data
    elif config.experiment in ["td_2", "td_10"]:
        return game_data_to_model_value_training_set(game_data, player.model), game_data
    elif config.experiment in ["td_lambda"]:
        lam = config.td_lambda
        return game_data_to_td_lambda_training_set(game_data, player.model, lam), game_data
    else:
        return game_data_to_training_set(game_data), game_data

def self_play(player: A0Player) -> tuple[list[ExperienceData], list[GameData]]:
    '''
    Runs self-play to generate a training set for the AlphaZero model.
    This function uses multiprocessing to run multiple games in parallel.
    The training set is generated from the game data, which is then returned.
    The game data can also be saved to a file if a filepath is provided.
    Args:
        player (A0Player): The player to use for self-play.
    Returns:
        The generated training set, containing board states, values, and policies.
        The game data for each game played, which can be used for analysis or debugging.
    '''
    logger.info("Starting self-play to generate training data...")
    # serialize the player model (JAX models cannot be pickled directly + serialization is needed for multiprocessing)
    player_serialized: bytes = dill.dumps(player)
    # use self-play with the model and mcts to generate training data
    # run each game in parallel
    game_data_list: list[GameData] = []
    training_set: list[ExperienceData] = []
    num_cores = config.num_workers
    logger.info(f"Using {num_cores} cores for self-play.")
    with concurrent.futures.ProcessPoolExecutor(max_workers=num_cores, max_tasks_per_child=1) as executor:
        # create a list to hold the futures
        futures: list[Future[tuple[list[ExperienceData], GameData]]] = []

        # create a function to start a game
        def start_game() -> None:
            future = executor.submit(
                _play,
                serialized_player=player_serialized
            )
            futures.append(future)
        
        # start a game for each core
        for _ in range(num_cores):
            start_game()
        
        while True:
            logger.info(f"Current training set size: {len(training_set)}/{config.training_samples}")
            # when a game (or games) finish(es),
            done, _ = wait(futures, return_when=FIRST_COMPLETED)

            # for each finished game,
            for future in done:
                # remove it from the list of futures
                futures.remove(future)
                # get the training data and game data from the game
                game_training_set, game_data = future.result()
                # add the training data to the training set
                training_set.extend(game_training_set)
                # and the game data to the list of game data
                game_data_list.append(game_data)
                # if the training set is not full yet, start a new game
                if len(training_set) < config.training_samples:
                    start_game()
            
            # stop when the training set is full
            if len(training_set) >= config.training_samples:
                logger.info("Training set is full, cancelling all games.")
                # cancel any submitted but not yet started games
                for future in futures:
                    future.cancel()
                # note the following does not immediately stop all processes,
                # but prevents new tasks from being started
                # and frees this main process to continue
                # the remaining games/processes finish in the background
                # executor.shutdown(wait=False)
                break
    
    logger.info(f"Generated training set of size: {len(training_set)}/{config.training_samples}")
    return training_set, game_data_list

def get_most_recent_model_path() -> Optional[tuple[str, int]]:
    '''
    Returns the path to the most recent model in the training directory,
    along with its iteration number.
    If no models are found, returns None.
    '''
    if not config.training_dir:
        return None
    model_files = [
        f for f in os.listdir(config.training_dir)
        if f.startswith("model_") and f.endswith(".pkl")
    ]
    if not model_files:
        return None
    # get the model with the highest iteration number
    max_iteration = -1
    most_recent_model_file = ""
    for f in model_files:
        iteration_str = f[len("model_"):-len(".pkl")]
        try:
            iteration = int(iteration_str)
            if iteration > max_iteration:
                max_iteration = iteration
                most_recent_model_file = f
        except ValueError:
            continue
    if max_iteration == -1:
        return None
    return (os.path.join(config.training_dir, most_recent_model_file), max_iteration)

def train_alphazero() -> None:
    os.makedirs(config.plot_dir + "training_plots", exist_ok=True)

    most_recent_model = get_most_recent_model_path()
    if most_recent_model is not None:
        model_path, starting_iteration = most_recent_model
        logger.info(f"Resuming training from model: {model_path} at iteration {starting_iteration}")
    else:
        model_path = None
        starting_iteration = 0
        logger.info("Starting new training from scratch.")
    
    if model_path:
        model = load_model(model_path)
    else:
        model = create_model(
            config.board_size,
            rngs=nnx.Rngs({'params': jax.random.PRNGKey(0)})
        )
        save_model(config.training_dir + f'/model_{0}.pkl', model)
    
    experience_buffer = ExperienceBuffer(
        config.replay_buffer_size
    )

    # Generate a balanced GT eval dataset once for value diagnostics
    gt_eval_boards, gt_eval_values = generate_balanced_gt_eval_dataset(n_samples=1000)

    iterations = config.training_iterations
    train_datas: list[DatasetData] = []
    logger.log(25, GameDataStats.get_header())
    for i in range(starting_iteration, iterations):
        print(f"Iteration {i + 1}/{iterations}")
        logger.info(f"Iteration {i + 1}/{iterations}")
        # create a player with the current model
        player = A0Player(
            config.board_size,
            config.num_pieces,
            model,
            mcts_samples=config.mcts_samples,
            no_reverse_moves=not config.backwards_moves,
            no_illegal_moves=not config.illegal_moves,
            no_side_moves=not config.sideways_moves,
            rollout_type=config.rollout_type,
            rollout_depth=config.rollout_depth,
            policy_type=config.policy_type,
            epsilon=config.epsilon,
            dirichlet_epsilon=config.dirichlet_epsilon
        )

        # generate training data with self-play
        training_set, game_data = self_play(player)

        # generate and print stats about the game data
        game_data_stats = game_data_list_stats(i, game_data)
        logger.log(25, f"{game_data_stats.get_line()}")
        
        # save the game data to a file
        if config.training_dir:
            with open(config.training_dir + f"gamedata_{i + 1}.pkl", 'wb') as f:
                pickle.dump(game_data, f)
        
        # add the training data to the replay buffer
        for example in training_set:
            experience_buffer.add(example)
        
        # get a dataset from the replay buffer for training, and train the model on it
        eb_dataset = experience_buffer.get_dataset(config.training_batch_size)
        # print the distribution of values in the dataset
        win_count, draw_count, loss_count = eb_dataset.get_distribution()
        logger.log(25, f"Experience buffer dataset distribution: {win_count} wins, {draw_count} draws, {loss_count} losses")
        eb_dataset.print_bucket_distribution()
        pre_balance_values = eb_dataset.values.flatten().copy()
        if config.experiment in ["gt", "gt_value", "gt_next_value"]:
            # and remove the bias
            eb_dataset.balance_values()
            new_win_count, new_draw_count, new_loss_count = eb_dataset.get_distribution()
            logger.log(25, f"After balancing: {new_win_count} wins, {new_draw_count} draws, {new_loss_count} losses")
            eb_dataset.print_bucket_distribution()
            logger.log(25, "---")
        
        if config.experiment == "td_2":
            logger.log(25, "Balancing values into 2 buckets (win vs non-win)...")
            eb_dataset.balance_values_symmetric(n_buckets=2)
            eb_dataset.print_bucket_distribution()
        elif config.experiment == "td_10":
            logger.log(25, "Balancing values into 10 buckets...")
            eb_dataset.balance_values_symmetric(n_buckets=10)
            eb_dataset.print_bucket_distribution()
        
        if config.experiment in ["td_lambda"]:
            lam = config.td_lambda
            logger.log(25, f"Using TD(lambda) with lambda={lam:.2f} for value targets.")
            # the dataset already has the TD(lambda) targets in the values field, so just balance them
            # value chosen based on the previous experiments...
            eb_dataset.balance_values_symmetric(n_buckets=2)
            eb_dataset.print_bucket_distribution()
        
        # capture value diagnostics: dataset distributions + model predictions on GT eval set
        post_balance_values = eb_dataset.values.flatten().copy()
        value_diagnostics = capture_value_diagnostics(
            model, pre_balance_values, post_balance_values,
            gt_eval_boards, gt_eval_values
        )
        if config.training_dir:
            with open(config.training_dir + f"value_diagnostics_{i + 1}.pkl", 'wb') as f:
                pickle.dump(value_diagnostics, f)

        # train the model on the experiences in the replay buffer
        model, train_data = train_model_epochs(
            model=model,
            dataset=eb_dataset,
            num_epochs=1,
            save="none",
            plot=False,
            test_datasets={}
        )
        train_datas.append(train_data)

        # plot, log, and save the model performance metrics in this iteration's training
        plot_model_performance(f"training_plots/iteration_{i + 1}", [train_data])
        save_dataset_data(
            f"{config.training_dir}/iteration_stats_{i + 1}.pkl",
            train_data
        )
        total, value_loss, policy_loss, value_accuracy, policy_accuracy = stats_from_dataset_data(train_data)
        logger.log(25, f"Iteration {i + 1} stats: Total Loss: {total:.4f}, Value Loss: {value_loss:.4f}, Policy Loss: {policy_loss:.4f}, Value Accuracy: {value_accuracy:.2%}, Policy Accuracy: {policy_accuracy:.2%}")

        # save the model after each iteration
        if config.training_dir:
            save_model(config.training_dir + f'model_{i + 1}.pkl', model)

        # free stale JIT caches and unreferenced GPU memory before the next iteration
        jax.clear_caches()
        gc.collect()

    # after all iterations, plot all the training data
    plot_model_performance("training_plots/full_a0", train_datas)

if __name__ == "__main__":
    setup_logging(
        level=20,
        log_dir=config.log_dir,
        process_name="training_alphazero"
    )

    logger.info(f"config: {config.path}")

    # Set the multiprocessing start method to 'spawn' for compatibility with JAX
    try:
        multiprocessing.set_start_method('spawn')
    except RuntimeError:
        pass

    # Example usage
    train_alphazero()
