'''
Target construction: converts self-play GameData into training examples.
Each game_data_to_*_training_set function implements one target type; the
build_training_set dispatcher picks the one selected by config.alternative_target.
Moved out of a0/train/alphazero.py (pure move, no behavior change).
'''
import jax
import jax.numpy as jnp
import numpy as np

from config import config

from a0.game import GameData
from a0.experience_buffer import ExperienceData
from a0.model_utils import board_to_input, get_legal_move_mask_from_state, Policy
from a0.model import AlphaZeroModel, MultiTrunkAlphaZeroModel
from cc.core import Player
from cc.ground_truth import GroundTruth

from utils.log import get_logger
logger = get_logger(__name__)

def terminal_value(game_data: GameData) -> float:
    '''
    z: game outcome from the LAST state's player's perspective.
    0.0 for draws and unfinished (turn-limit) games.
    '''
    game_winner = game_data.winner
    if game_winner is None:
        return 0.0
    return 1.0 if game_winner == game_data.turn_data[-1].board.current_player else -1.0

def td_lambda_targets(model_values: np.ndarray, z: float, lam: float) -> list[float]:
    '''
    Backward TD(lambda) recursion over a single game.
      G_{T-1}^\\lambda = z   (game outcome from last player's perspective)
      G_t^\\lambda = -(1 - \\lambda) \\hat{v}(S_{t+1}) - \\lambda G_{t+1}^\\lambda
    Both terms are negated because \\hat{v}(S_{t+1}) and G_{t+1}^\\lambda
    are from the next player's (opponent's) perspective.
    model_values: per-turn value estimates, shape (T, 1) or (T,); only
    indices 1..T-1 are read (may be arbitrary when lam == 1).
    '''
    num_turns = len(model_values)
    targets = [0.0] * num_turns
    targets[-1] = z
    for t in range(num_turns - 2, -1, -1):
        v_next = float(np.asarray(model_values[t + 1]).reshape(-1)[0])  # \hat{v}(S_{t+1})
        targets[t] = -(1 - lam) * v_next - lam * targets[t + 1]
    return targets

def game_data_to_training_set(game_data: GameData) -> list[ExperienceData]:
    '''
    Converts a game data object generated by a game into a training set.
    Each turn in the game data is transformed into a training example.
    '''
    training_set: list[ExperienceData] = []
    # get the game data and transform it into training data
    game_winner = game_data.winner

    turn_data = game_data.turn_data
    for turn in turn_data:
        # get the board state
        board = turn.board

        # get the mask for full legal moves
        legal_move_mask = get_legal_move_mask_from_state(board, for_model=True)

        # get the outcome of the game for the current player
        current_player = board.current_player
        if game_winner is None:
            # draws and unfinished games
            value = 0.0
        else:
            # 1 for win, -1 for loss
            # based on the perspective of the current player
            value = 1.0 if game_winner == current_player else -1.0

        # get the policy distribution generated by MCTS (already np from Policy class)
        mcts_policy = turn.player_data

        # create a training example
        training_example: ExperienceData = ExperienceData(
            board=board_to_input(board),
            value=value,
            policy=mcts_policy,
            mask=legal_move_mask
        )

        # add it to the training set
        training_set.append(training_example)

        # add both to alternative targets
        turn.alternative_value_target = value
        turn.alternative_policy_target = mcts_policy

    return training_set

def game_data_to_gt_training_set(game_data: GameData, gt: GroundTruth | None = None) -> list[ExperienceData]:
    '''
    Converts a game data object generated by a game into a training set.
    Each turn in the game data is transformed into a training example.
    Except this function uses the ground truth data for the value/policy at each state,
    rather than the "experienced" outcome/policy.
    '''
    if gt is None:
        gt = GroundTruth()
    training_set: list[ExperienceData] = []

    turn_data = game_data.turn_data
    for turn in turn_data:
        # get the board state
        board = turn.board

        # get the mask for full legal moves
        legal_move_mask = get_legal_move_mask_from_state(board, for_model=True)

        # get the gt outcome of the board for the current player
        value = gt.get_outcome(board)

        # get the gt policy distribution (list[float] from GroundTruth, needs np conversion)
        mcts_policy = np.array(gt.get_1ply_policy_prob_dist_list(board, for_model=True), dtype=np.float32)

        # create a training example
        training_example: ExperienceData = ExperienceData(
            board=board_to_input(board),
            value=value,
            policy=mcts_policy,
            mask=legal_move_mask
        )

        # add it to the training set
        training_set.append(training_example)

        # add both to alternative targets
        turn.alternative_value_target = value
        turn.alternative_policy_target = mcts_policy

    return training_set

def game_data_to_gt_value_training_set(game_data: GameData, gt: GroundTruth | None = None) -> list[ExperienceData]:
    '''
    Like game_data_to_training_set, but replaces the value with the ground truth
    outcome of the current state. The policy is kept as the MCTS policy.
    '''
    if gt is None:
        gt = GroundTruth()
    training_set: list[ExperienceData] = []

    turn_data = game_data.turn_data
    for turn in turn_data:
        board = turn.board
        legal_move_mask = get_legal_move_mask_from_state(board, for_model=True)

        # GT value for the current state
        value = gt.get_outcome(board)

        # MCTS policy (already in model perspective)
        mcts_policy = turn.player_data

        training_example = ExperienceData(
            board=board_to_input(board),
            value=value,
            policy=mcts_policy,
            mask=legal_move_mask
        )
        training_set.append(training_example)

        # add both to alternative targets
        turn.alternative_value_target = value
        turn.alternative_policy_target = mcts_policy

    return training_set

def game_data_to_gt_next_value_training_set(game_data: GameData, gt: GroundTruth | None = None) -> list[ExperienceData]:
    '''
    Like game_data_to_training_set, but replaces the value with the ground truth
    outcome of the next state, where the top action in the MCTS policy is taken
    on the current state. The policy is kept as the MCTS policy.
    The GT outcome of the next state is from the opponent's perspective,
    so it is negated to stay in the current player's perspective.
    '''
    if gt is None:
        gt = GroundTruth()
    training_set: list[ExperienceData] = []

    turn_data = game_data.turn_data
    for turn in turn_data:
        board = turn.board
        legal_move_mask = get_legal_move_mask_from_state(board, for_model=True)

        # The stored MCTS policy is in model perspective (rotated for PLAYER_O).
        # Un-rotate to find the actual best move on the board.
        mcts_policy = turn.player_data
        p = Policy(len(board.board))
        p.set_logits(mcts_policy.copy(), rotate_180=False)
        if board.current_player == Player.PLAYER_O:
            p.rotate_policy()
        best_move = p.get_best_move()

        # Apply the best move to get the next state
        board.apply_move(best_move)
        # GT outcome from the next state's current player (opponent), negated
        value = -gt.get_outcome(board)
        board.undo_move(best_move)

        training_example = ExperienceData(
            board=board_to_input(board),
            value=value,
            policy=mcts_policy,
            mask=legal_move_mask
        )
        training_set.append(training_example)

        # add both to alternative targets
        turn.alternative_value_target = value
        turn.alternative_policy_target = mcts_policy

    return training_set

def game_data_to_model_value_training_set(game_data: GameData, model: AlphaZeroModel | MultiTrunkAlphaZeroModel) -> list[ExperienceData]:
    '''
    Like game_data_to_training_set, but uses backward-propagated model values as targets.
    The last state's target is the true game outcome. For all earlier states, the target
    is the negated model value of the next state (negated because players alternate).
    The policy is kept as the MCTS policy.
    Also populates turn.alternative_value_target
    the model's predictions are saved with the game data.
    '''
    training_set: list[ExperienceData] = []

    turn_data = game_data.turn_data
    if not turn_data:
        return training_set

    # batch all board inputs for a single inference call
    board_inputs = [board_to_input(turn.board) for turn in turn_data]
    boards = np.concatenate(board_inputs, axis=0)
    model_values, _ = model.inference(boards)
    model_values = np.asarray(jax.lax.stop_gradient(model_values))

    # compute targets backward from the last state: this is exactly the
    # TD(lambda) recursion with lam=0 (target = -V(s_{t+1}), terminal = z)
    targets = td_lambda_targets(model_values, terminal_value(game_data), 0.0)

    for turn, board_input, target in zip(turn_data, board_inputs, targets):
        turn.alternative_value_target = target

        legal_move_mask = get_legal_move_mask_from_state(turn.board, for_model=True)
        training_example = ExperienceData(
            board=board_input,
            value=target,
            policy=turn.player_data,
            mask=legal_move_mask
        )
        training_set.append(training_example)

        # add both to alternative targets
        turn.alternative_value_target = target
        turn.alternative_policy_target = turn.player_data

    return training_set

def game_data_to_td_lambda_training_set(game_data: GameData, model: AlphaZeroModel | MultiTrunkAlphaZeroModel, lam: float) -> list[ExperienceData]:
    '''
    Uses TD(lambda) targets to blend bootstrapped and Monte Carlo returns.
      - lambda=0: TD(0), target = -V(s_{t+1})
      - lambda=1: Monte Carlo, target = game outcome
    Recursive formula (backward pass):
      G_{T-1} = z_{T-1}
      G_t     = -(1 - lambda) * V[t+1] - lambda * G_{t+1}
    The policy is kept as the MCTS policy.
    '''
    training_set: list[ExperienceData] = []
    turn_data = game_data.turn_data
    if not turn_data:
        return training_set

    # \hat{v}(S_0), \hat{v}(S_1), ..., \hat{v}(S_{T-1}) via batch inference.
    # Run inference in fixed-size chunks: each chunk is padded to a single static
    # shape so the JIT still compiles only one kernel for this path, while peak GPU
    # memory is bounded by the chunk size instead of by turn_limit. Sizing the batch
    # to turn_limit made a long-turn_limit game allocate a huge forward pass in every
    # self-play worker, which OOMs the GPU when many workers run concurrently.
    INFERENCE_BATCH_SIZE = getattr(config, "self_play_value_inference_batch_size", 64)
    board_inputs = [board_to_input(turn.board) for turn in turn_data]
    boards = np.concatenate(board_inputs, axis=0)
    num_real = boards.shape[0]

    value_chunks = []
    for start in range(0, num_real, INFERENCE_BATCH_SIZE):
        chunk = boards[start:start + INFERENCE_BATCH_SIZE]
        chunk_len = chunk.shape[0]
        # pad the (possibly final) chunk up to the fixed size so the JIT sees one shape
        if chunk_len < INFERENCE_BATCH_SIZE:
            padding = np.zeros((INFERENCE_BATCH_SIZE - chunk_len, *chunk.shape[1:]), dtype=chunk.dtype)
            chunk = np.concatenate([chunk, padding], axis=0)
        chunk_values, _ = model.inference(chunk)
        value_chunks.append(chunk_values[:chunk_len])
    model_values = jnp.concatenate(value_chunks, axis=0)
    model_values = np.asarray(jax.lax.stop_gradient(model_values))

    # backward recursion (shared with the target-refresh path)
    targets = td_lambda_targets(model_values, terminal_value(game_data), lam)

    for turn, board_input, target in zip(turn_data, board_inputs, targets):
        turn.alternative_value_target = target
        legal_move_mask = get_legal_move_mask_from_state(turn.board, for_model=True)
        training_example = ExperienceData(
            board=board_input,
            value=target,
            policy=turn.player_data,
            mask=legal_move_mask
        )
        training_set.append(training_example)

        # add both to alternative targets
        turn.alternative_value_target = target
        turn.alternative_policy_target = turn.player_data

    return training_set

def resolve_td_lambda(iteration: int) -> float:
    '''
    The lambda in effect at this iteration:
      - "interpolated_td_lambda": linear interpolation, lam = 1 at iteration 0,
        decreasing to lam = 0 over config.interpolated_td_lambda_iterations
        iterations (falling back to 25% of training when unset), then 0.
      - otherwise: config.td_lambda (default 1.0 = plain MC targets).
    Shared by the self-play dispatch and the target-refresh path.
    '''
    if config.alternative_target == "interpolated_td_lambda":
        decay_iters = getattr(config, "interpolated_td_lambda_iterations", None)
        warmup = decay_iters if decay_iters else max((config.training_iterations - 1) * 0.25, 1)
        return max(1.0 - (iteration / warmup), 0.0)
    return getattr(config, "td_lambda", 1.0)

def resolve_num_target_refreshes(iteration: int) -> int:
    '''
    K (refreshes/iteration) in effect at this iteration, for the target-refresh
    path. If config.refresh_k_decay_iterations is set, K decays linearly from
    config.num_target_refreshes at iteration 0 to 1 at that iteration, then
    holds at 1 (never 0: refresh-0 semantics — the alternative_value_target
    saved for eval3 — require at least one pass every iteration). Otherwise
    constant at config.num_target_refreshes.
    '''
    k0 = max(1, getattr(config, "num_target_refreshes", 1))
    decay_iters = getattr(config, "refresh_k_decay_iterations", None)
    if not decay_iters:
        return k0
    frac = max(1.0 - (iteration / decay_iters), 0.0)
    return max(1, round(k0 * frac))

def build_training_set(game_data: GameData, model: AlphaZeroModel | MultiTrunkAlphaZeroModel, iteration: int) -> list[ExperienceData]:
    '''
    Dispatches to the target builder selected by config.alternative_target.
    (Moved from the if/elif chain in _play.)
    '''
    if config.alternative_target == "gt":
        return game_data_to_gt_training_set(game_data)
    elif config.alternative_target == "gt_value":
        return game_data_to_gt_value_training_set(game_data)
    elif config.alternative_target == "gt_next_value":
        return game_data_to_gt_next_value_training_set(game_data)
    elif config.alternative_target == "td_0":
        return game_data_to_model_value_training_set(game_data, model)
    elif config.alternative_target == "td_lambda":
        return game_data_to_td_lambda_training_set(game_data, model, resolve_td_lambda(iteration))
    elif config.alternative_target == "interpolated_td_lambda":
        lam = resolve_td_lambda(iteration)
        logger.info(f"interpolated_td_lambda: iteration={iteration}, lam={lam:.4f}")
        return game_data_to_td_lambda_training_set(game_data, model, lam)
    else:
        return game_data_to_training_set(game_data)
