from a0.eval.training_data import game_data_generator
from cc.ground_truth import GroundTruth
from a0.model_utils import Policy
from cc.core import Player, Game, Board
from a0.eval.dataset_evaluation import policy_accuracy_function

from jax import numpy as jnp
import numpy as np

from config import config

from utils.log import get_logger, setup_logging
logger = get_logger(__name__)

def print_policy(board: Board, game: Game, mcts_policy: Policy, gt_policy: Policy):
    '''
    Prints the policy in a human-readable format.
    '''
    acc = policy_accuracy_function(np.array(mcts_policy.get_policy_list()), np.array(gt_policy.get_policy_list()))

    # get the moves for the current board
    moves = game.generate_moves_for_given_board(board)

    # get the move probabilities (both the MCTS and GT)
    mcts_probs: list[float] = []
    gt_probs: list[float] = []
    towards_goal: list[str] = []
    for move in moves:
        is_up = move.is_up()
        is_down = move.is_down()
        if not is_up and not is_down:
            towards_goal.append("side move")
        elif is_up and board.current_player == Player.PLAYER_O or is_down and board.current_player == Player.PLAYER_X:
            towards_goal.append("forward move")
        else:
            towards_goal.append("backward move")
        mcts_probs.append(mcts_policy.get_move_probability(move))
        gt_probs.append(gt_policy.get_move_probability(move))
    
    # sort by MCTS probabilities
    zipped = list(zip(mcts_probs, gt_probs, moves, towards_goal))
    zipped.sort(key=lambda x: x[0], reverse=True)

    # print summary
    logger.info(f" Policy distribution for current player (p sum {sum(mcts_probs):.2%}, Acc: {acc}):")
    
    # print sorted moves
    for mcts_prob, gt_prob, move, direction in zipped:
        logger.info(f" {move}, P: {mcts_prob:.2%}, GT: {gt_prob:.1f}, {direction}")
    
    return acc

def main():
    gd_gen = game_data_generator(config.training_dir, config.training_iterations)
    gt = GroundTruth()
    game = Game(
        board_size=config.board_size,
        num_pieces=config.num_pieces,
        no_reverse_moves=False
    )

    total_states = 0
    total_acc = 0

    ins_it = None
    ins_g = None

    for it, gdl in gd_gen:
        #logger.info(f"Iteration {it}, number of games: {len(gdl)}")
        if ins_it and it != ins_it:
            continue
        for gi, gd in enumerate(gdl):
            if ins_g and gi != ins_g:
                continue

            if gd.winner is None and not gd.ended:
                #logger.info(f" Game {gi} was a draw, skipping.")
                continue
        
            logger.info(f" Game {gi}, ended: {gd.ended}, winner: {gd.winner}, turns: {len(gd.turn_data)}")
            game_winner = gd.winner 
            for ti, td in enumerate(gd.turn_data):
                board = td.board

                # skip trivial boards and boards that are not the last turn
                # if gt.is_trivial(board) or ti < len(gd.turn_data) - 1 or board.current_player == Player.PLAYER_X:
                #     continue
                if gt.is_trivial(board):
                    continue

                logger.info(f"  Turn {ti}, move: {td.move}")
                logger.info(f"  Board state:\n{td.board.board_view()}")
                logger.info(f"  {board.current_player}")

                # get the outcome of the game for the current player
                current_player = board.current_player
                if game_winner is None:
                    value = 0.0
                else:
                    value = 1.0 if game_winner == current_player else -1.0
                # get the gt value
                gt_value = gt.get_outcome(board)

                logger.info(f"  From {current_player} perspective, game outcome value: {value}, GT outcome: {gt_value}")

                # get the policy distribution generated by MCTS (note: in "model" perspective)
                mcts_policy: jnp.ndarray = td.player_data
                p = Policy(config.board_size)
                p.set_logits(np.array(mcts_policy), rotate_180=current_player == Player.PLAYER_O)
                # get the gt policy
                gt_policy = gt.get_1ply_policy_outcomes_list(board, for_model=False)
                gtp = Policy(config.board_size)
                gtp.set_logits(np.array(gt_policy), rotate_180=False)

                acc = print_policy(board, game, p, gtp)

                total_states += 1
                if acc:
                    total_acc += 1

                if gd.final_board:
                    logger.info(f" Final board state:\n{gd.final_board.board_view()}")
                
                logger.info(f"Overall policy accuracy over inspected states: {total_acc}/{total_states} = {total_acc/total_states:.2%}")


if __name__ == "__main__":
    setup_logging(
        level=20,
        log_dir=config.log_dir,
        process_name="itd"
    )

    main()