import random
from tqdm import tqdm
import jax.numpy as jnp
import numpy as np

from a0.eval.dataset_evaluation import policy_accuracy_function
from a0.eval.training_data import game_data_generator
from a0.model_utils import get_legal_move_mask_from_state
from cc.core import Board, Game
from cc.ground_truth import GroundTruth
from a0.dataset import Dataset
from a0.experience_buffer import ExperienceData
from a0.train.alphazero import board_to_input
from a0.eval.training_data import game_data_generator
from a0.train.generate_datasets import generate_ground_truth_dataset, load_ground_truth_dataset
from a0.train.dataset import train_model_on_given_dataset

from config import config

from utils.log import get_logger, setup_logging
logger = get_logger(__name__)

def get_generated_gamedata_dataset(n: int | None = None, simulated: bool = False, sim_value_acc: float = 0.5, sim_policy_acc: float = 0.5) -> tuple[Dataset, set[Board]]:
    '''
    This function generates a dataset of game data by either using real or simulated data.
    The real data comes from the gamedata_i.pkl files generated by alphazero training and stored in the training dir.
    n: The size of the dataset to generate
    simulated: Use real or simulated data
    sim_value_acc: The accuracy of the simulated value data
    sim_policy_acc: The accuracy of the simulated policy data
    '''
    logger.info("Generating experienced values from training data...")
    gt = GroundTruth()

    # 1. get the unique boards (with their outcome/policy) from the training data
    logger.info("Getting unique boards from training data, with their experienced outcome...")
    game_data_lists = game_data_generator(config.training_dir, config.training_iterations)
    total_boards = 0
    boards_set: set[ExperienceData] = set()
    unique_boards_set: set[Board] = set()
    total_value_acc = 0
    total_policy_acc = 0
    total_sim_value_acc = 0
    for _, game_data_list in tqdm(game_data_lists):
        for game_data in game_data_list:
            game_winner = game_data.winner
            turn_data = game_data.turn_data
            for turn in turn_data:
                # get the board and its experienced outcome (current player perspective)
                board = turn.board
                experienced_outcome = 0.0 if game_winner is None else 1.0 if game_winner == board.current_player else -1.0
                experienced_policy = turn.player_data

                unique_boards_set.add(board)

                ground_truth_outcome = gt.get_outcome(board)
                ground_truth_policy = jnp.array(gt.get_1ply_policy_prob_dist_list(board, for_model=True))

                # sim_value_acc percent of the time, use ground truth. otherwise, use the incorrect label.
                simulated_outcome = ground_truth_outcome if random.random() < sim_value_acc else 1 - ground_truth_outcome

                if experienced_outcome == ground_truth_outcome:
                    total_value_acc += 1
                if policy_accuracy_function(experienced_policy, np.array(ground_truth_policy)):
                    total_policy_acc += 1

                if simulated_outcome == ground_truth_outcome:
                    total_sim_value_acc += 1
                
                legal_move_mask = get_legal_move_mask_from_state(board, for_model=True)

                if simulated:
                    experience = ExperienceData(jnp.array(board_to_input(board)), simulated_outcome, jnp.zeros_like(experienced_policy), jnp.array(legal_move_mask))
                else:
                    experience = ExperienceData(jnp.array(board_to_input(board)), experienced_outcome, jnp.zeros_like(experienced_policy), jnp.array(legal_move_mask))
                
                # add this to a set
                boards_set.add(experience)
                total_boards += 1
    
    num_unique = len(boards_set)
    num_unique_boards = len(unique_boards_set)
    logger.info(f"Found {num_unique_boards} unique boards in the game data, out of {total_boards} total boards ({(num_unique_boards/total_boards)*100:.2f}%).")
    logger.info(f"Found {num_unique} unique boards+value+policy triplets in the game data, out of {total_boards} total boards ({(num_unique/total_boards)*100:.2f}%).")
    logger.info(f"Training data value accuracy: {total_value_acc/total_boards:.2%}, policy accuracy: {total_policy_acc/total_boards:.2%}.")
    logger.info(f"Simulated value accuracy: {total_sim_value_acc/total_boards:.2%} (intended {sim_value_acc:.2%}).")

    boards = list(boards_set)
    if n is not None: boards = random.sample(boards, n)
    
    # 4. load all this into a Dataset object
    ev_dataset = Dataset(batch_size=256)
    e_board = jnp.stack([d.board for d in boards]) # (board_size, board_size) -> (N, board_size, board_size)
    e_value = jnp.array([d.value for d in boards])[:, None] # Add [:, None] to make its shape (N, 1)
    e_policy = jnp.stack([d.policy for d in boards]) # (board_size ** 4) -> (N, board_size ** 4)
    e_mask = jnp.stack([d.mask for d in boards]) # (board_size ** 4) -> (N, board_size ** 4)
    logger.info(f"states.shape: {e_board.shape}, values.shape: {e_value.shape}, policies.shape: {e_policy.shape}, masks.shape: {e_mask.shape}")
    ev_dataset.set(e_board, e_value, e_policy, e_mask)

    return ev_dataset, unique_boards_set

def main():
    '''
    This script trains a model on generated game data OR simulated game data.
    It uses the ground truth dataset for evaluation.
    To generate the dataset (when using generated gamedata),
    it pulls the gamedata_i.pkl files in the training dir.
    It saves files to the training dir (model performance) and plot dir (training graphs).
    '''
    simulated = False
    dataset_size = 50000

    setup_logging(
        level=20,
        log_dir=config.log_dir,
        process_name="train_on_generated_gamedata"
    )

    logger.info(f"Using {'simulated' if simulated else 'real'} game data for training, with dataset size {dataset_size}.")

    if simulated:
        train_dataset = get_generated_gamedata_dataset(50000, simulated=True, sim_value_acc=0.5377, sim_policy_acc=0.4239)
    else:
        train_dataset = get_generated_gamedata_dataset(50000)
    train_dataset.shuffle()

    # try to load the ground truth dataset, if it exists
    # if not, generate it
    try:
        gt_dataset = load_ground_truth_dataset()
        logger.info("Ground truth dataset loaded successfully.")
    except FileNotFoundError:
        logger.warning(f"Dataset file was not found. Generating ground truth dataset...")
        # If the dataset does not exist, generate it
        generate_ground_truth_dataset()
        gt_dataset = load_ground_truth_dataset()
    
    # process the dataset (trim it, create train-test split, etc.)
    gt_dataset.trim(100000, shuffle=False)
    gt_dataset_test = gt_dataset.split_off_test(len(gt_dataset) // 10, shuffle=True)

    train_model_on_given_dataset(train_dataset, num_epochs=1, save_type='batch', test_dataset=gt_dataset_test)

if __name__ == "__main__":
    main()
